belaybingo/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("routes/", include("routes.urls")),
    path("accounts/", include("accounts.urls")),
    path("ascents/", include("ascents.urls")),
    path("bingo/", include("bingoboard.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_routes")),
        name="home",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

routes/urls.py
from django.urls import path
from routes.views import RouteListView, CreateRouteView, RouteDetailView, EditRouteView

urlpatterns = [
    path("", RouteListView.as_view(), name="list_routes"),
    path("create/", CreateRouteView.as_view(), name="create_route"),
    path("<int:pk>/", RouteDetailView.as_view(), name="show_route"),
    path("<int:pk>/edit/", EditRouteView.as_view(), name="edit_route"),
]

routes/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Route(models.Model):
    class RouteType(models.TextChoices):
        TRAD = "Trad"
        SPORT = "Sport"

    class LetterRating(models.TextChoices):
        A = "a"
        B = "b"
        C = "c"
        D = "d"

    name = models.CharField(max_length=250)
    location = models.CharField(max_length=200, null=True)
    type = models.CharField(
        max_length=5, choices=RouteType.choices, default=RouteType.TRAD
    )
    grade = models.CharField(max_length=5, null=True)
    letter_rating = models.CharField(
        max_length=4, choices=LetterRating.choices, null=True, blank=True
    )
    pitches = models.PositiveSmallIntegerField(null=True)
    length = models.PositiveSmallIntegerField(null=True, blank=True)
    description = models.TextField(null=True)
    protection = models.TextField(null=True)
    image = models.ImageField(null=True, upload_to="images/", blank=True)

    def __str__(self) -> str:
        return self.name

    def getRating(self):
        if self.letter_rating != None:
            return self.grade + self.letter_rating
        return self.grade

routes/admin.py
from django.contrib import admin
from routes.models import Route

# Register your models here.


class RouteAdmin(admin.ModelAdmin):
    pass


admin.site.register(Route, RouteAdmin)

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'

routes/tests.py
from django.test import TestCase

# Create your tests here.

routes/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from routes.models import Route
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from ascents.models import Ascent

# Create your views here.
class RouteListView(ListView):
    model = Route
    template_name = "routes/list.html"


class CreateRouteView(CreateView):
    model = Route
    template_name = "routes/new.html"
    fields = [
        "name",
        "location",
        "type",
        "grade",
        "letter_rating",
        "pitches",
        "length",
        "description",
        "protection",
        "image",
    ]

    def form_valid(self, form):
        route = form.save(commit=False)
        route.save()
        return redirect("list_routes")


class RouteDetailView(DetailView):
    model = Route
    template_name = "routes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ascents = []
        if self.request.user.is_authenticated:
            for ascent in self.request.user.ascents.all():
                ascents.append(ascent)
        context["ascents_for_route"] = ascents
        return context


class EditRouteView(UpdateView):
    model = Route
    template_name = "routes/edit.html"
    fields = [
        "name",
        "location",
        "type",
        "grade",
        "letter_rating",
        "pitches",
        "length",
        "description",
        "protection",
        "image",
    ]

    def form_valid(self, form):
        route = form.save(commit=False)
        route.save()
        return redirect("show_route", pk=route.id)

routes/templates/routes/detail.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-detail">
          <h1>{{route.name}}</h1>
          <div class="image-detail">
            <p>
              <img src="../../media/{{ route.image }}" width = '200'>
            </p>
          <div class="route-detail">
            <p>Route description: {{route.description}}</p>

            <p>
              Location: {{route.location}}
            </p>
            <p>
              Climb type: {{route.type}}
            </p>
            <p>
              Grade: {{route.getRating}}
            </p>
            <p>
              <a href="{% url 'edit_route' route.id %}">Edit route details</a>
          </p>
          {% if ascents_for_route|length == 0 %}
            <p>
              You haven't climbed this route yet!
            </p>
            {% else %}
          <p>You climbed this route on: </p>
          {% for ascent in ascents_for_route %}
            {% if ascent.route.name == route.name %}
            <li>{{ascent.date}}: {{ascent.type}}</li>
            {% endif %}
          {% endfor %}
          {% endif %}
      </div>
    </div>
  </div>
    </main>
{% endblock content %}

routes/templates/routes/edit.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form">
            <h1>Edit</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Update</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

routes/templates/routes/list.html
{% extends 'base.html' %}

{% block content %}
<main class="route-grid">
  {% for route in route_list %}
    <div class="route-grid-entry">
      <h2 class="route-card-title"><a href="{% url 'show_route' route.id %}">{{route.name}}</a></h2>
      <p class="route-card-grade">{{route.getRating}}</p>
      <p class="route-grid-image"><img src="../media/{{ route.image }}" height = '200'></p>
      <p class="route-card-location">{{route.location}}</p>
  </div>
  {% endfor %}
</main>

{% endblock content %}

routes/templates/routes/new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form">
            <h1>Add a route</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}