ascents/urls.py
from unicodedata import name
from django.urls import path

from ascents.views import (
    AscentListView,
    AscentDetailView,
    AscentCreateView,
    AscentEditView,
)

urlpatterns = [
    path("ascents/", AscentListView.as_view(), name="ascents"),
    path("<int:pk>/", AscentDetailView.as_view(), name="show_ascent"),
    path("create/", AscentCreateView.as_view(), name="create_ascent"),
    path("<int:pk>/edit/", AscentEditView.as_view(), name="edit_ascent"),
]

belaybingo/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("routes/", include("routes.urls")),
    path("accounts/", include("accounts.urls")),
    path("ascents/", include("ascents.urls")),
    path("bingo/", include("bingoboard.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_routes")),
        name="home",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

routes/urls.py
from django.urls import path
from routes.views import RouteListView, CreateRouteView, RouteDetailView, EditRouteView

urlpatterns = [
    path("", RouteListView.as_view(), name="list_routes"),
    path("create/", CreateRouteView.as_view(), name="create_route"),
    path("<int:pk>/", RouteDetailView.as_view(), name="show_route"),
    path("<int:pk>/edit/", EditRouteView.as_view(), name="edit_route"),
]

ascents/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Ascent(models.Model):
    class AscentType(models.TextChoices):
        TOPROPE = "Toprope"
        LEAD = "Lead"
        REDPOINT = "Redpoint"
        PINKPOINT = "Pinkpoint"
        ONSIGHT = "Onsight"

    route = models.ForeignKey(
        "routes.Route", related_name="ascents", on_delete=models.CASCADE
    )
    climber = models.ForeignKey(
        USER_MODEL, related_name="ascents", on_delete=models.SET_NULL, null=True
    )
    type = models.CharField(
        max_length=10, choices=AscentType.choices, default=AscentType.TOPROPE
    )
    date = models.DateField(null=True, blank=True)
    notes = models.TextField()

ascents/views.py
from audioop import reverse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from ascents.models import Ascent
from django.contrib.auth.mixins import LoginRequiredMixin
import operator
from django.shortcuts import redirect


# Create your views here.
class AscentListView(LoginRequiredMixin, ListView):
    model = Ascent
    template_name = "ascents/list.html"
    paginate_by = 10

    def get_queryset(self):
        filteredAscents = Ascent.objects.filter(climber=self.request.user)
        sortedAscents = filteredAscents.order_by("-date")
        return sortedAscents


class AscentDetailView(LoginRequiredMixin, DetailView):
    model = Ascent
    template_name = "ascents/detail.html"


class AscentCreateView(LoginRequiredMixin, CreateView):
    model = Ascent
    template_name = "ascents/new.html"
    fields = ["route", "type", "date", "notes"]

    def form_valid(self, form):
        ascent = form.save(commit=False)
        ascent.climber = self.request.user
        ascent.save()
        return redirect("ascents")


class AscentEditView(LoginRequiredMixin, UpdateView):
    model = Ascent
    template_name = "ascents/edit.html"
    fields = ["route", "type", "date", "notes"]
    success_url = reverse_lazy("ascents")

ascents/templates/ascents/detail.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="project-detail">
            <h1>{{ascent.name}}</h1>
            <p>{{ascent.date}}</p>
            <p>{{ascent.type}}</p>
            <p>{{ascent.notes}}</p>
            <a href="{% url 'edit_ascent' ascent.id %}">Edit ascent</a>
        </div>

    </main>
{% endblock content %}

ascents/templates/ascents/edit.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form">
            <h1>Edit</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Update</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

ascents/templates/ascents/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="my-tasks-list">
    <h1>My Ascents</h1>
    <a href="{% url 'create_ascent' %}">Add Ascent</a>
    {% if ascent_list|length == 0 %}
    <p>You have no ascents</p>
    {% else %}
    <table>
      <thead>
          <tr>
              <th>Route name</th>
              <th>Ascent date</th>
              <th>Ascent type</th>
          </tr>
      </thead>
      <tbody>
        {% for ascent in ascent_list %}
              <tr>
                  <td><a href="{% url 'show_ascent' ascent.id %}">{{ascent.route.name}}</a></td>
                  <td>{{ascent.date}}</td>
                  <td>{{ascent.type}}</td>
              </tr>

          {% endfor %}
      </tbody>
  </table>
  </div>
  {% endif %}
</main>

{% endblock content %}

ascents/templates/ascents/new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form">
            <h1>Add an ascent</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}