belaybingo/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("routes/", include("routes.urls")),
    path("accounts/", include("accounts.urls")),
    path("ascents/", include("ascents.urls")),
    path("bingo/", include("bingoboard.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_routes")),
        name="home",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bingoboard/urls.py
from django.urls import path

from bingoboard.views import (
    BingoGameListView,
    BingoGameBoardView,
    BingoGameBoardCreateView,
)

urlpatterns = [
    path("", BingoGameListView.as_view(), name="bingo_list"),
    path("<int:pk>/", BingoGameBoardView.as_view(), name="bingo_game"),
    path("create/", BingoGameBoardCreateView.as_view(), name="bingo_game_create"),
]

routes/urls.py
from django.urls import path
from routes.views import RouteListView, CreateRouteView, RouteDetailView, EditRouteView

urlpatterns = [
    path("", RouteListView.as_view(), name="list_routes"),
    path("create/", CreateRouteView.as_view(), name="create_route"),
    path("<int:pk>/", RouteDetailView.as_view(), name="show_route"),
    path("<int:pk>/edit/", EditRouteView.as_view(), name="edit_route"),
]

bingoboard/models.py
from django.db import models
from django.conf import settings
from abc import ABC, abstractmethod


USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class AbstractGoal(models.Model):
    @abstractmethod
    def get_text(self):
        return "Nothing"


class ClimbingGoal(AbstractGoal):
    route = models.ForeignKey(
        "routes.Route",
        related_name="climbing_goals",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self) -> str:
        return self.route.name

    def get_text(self):
        return self.route.name


class FunnyGoal(AbstractGoal):
    goal = models.CharField(max_length=200)

    def get_text(self):
        return self.goal

    def __str__(self) -> str:
        return self.goal


class BingoGame(models.Model):
    name = models.CharField(max_length=200, null=True)
    created_on = models.DateField(auto_now_add=True, null=True)
    climber = models.ForeignKey(
        USER_MODEL, related_name="bingo_games", on_delete=models.CASCADE, null=True
    )
    climbing_goal = models.ManyToManyField("ClimbingGoal", related_name="bingo_games")
    funny_goal = models.ManyToManyField("FunnyGoal", related_name="bingo_games")

    def __str__(self) -> str:
        return self.name

bingoboard/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from bingoboard.models import BingoGame
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
import random


class BingoGameListView(ListView):
    model = BingoGame
    template_name = "bingoboards/list.html"

    def get_queryset(self):
        return BingoGame.objects.filter(climber=self.request.user)


class BingoGameBoardView(DetailView):
    model = BingoGame
    template_name = "bingoboards/board.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        goals = []

        for game in BingoGame.objects.filter(pk=self.object.id):
            for goal in game.climbing_goal.all():
                goals.append(goal.route.name)
            for funny_goal in game.funny_goal.all():
                goals.append(funny_goal.goal)
        random.shuffle(goals)
        # cut the data off at length 9
        shortGoals = goals[:8]
        shortGoals.insert(4, "logo")
        context["goals_for_game"] = shortGoals
        return context


class BingoGameBoardCreateView(CreateView):
    model = BingoGame
    template_name = "bingoboards/new.html"
    fields = ["name", "climbing_goal", "funny_goal"]

    def form_valid(self, form):
        game = form.save(commit=False)
        game.climber = self.request.user
        game.save()
        form.save_m2m()
        return redirect("bingo_game", pk=game.id)

bingoboard/templates/bingoboards/board.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<h1 class="title">{{bingogame.name}}</h1>
<main class="bingo-card">

  {% for goal in goals_for_game %}
    {% if goal == "logo" %}
      <div class="bingo-card-free-space">
        <img src="{% static 'img/kg-chalk-bag-01.png' %}" alt="" height='120'>
      </div>
    {% else %}
      <div class="bingo-card-entry">
        <h2 class="bingo-card-goal">{{goal}}</h2>
      </div>
    {% endif %}
  {% endfor %}
</main>

{% endblock content %}

bingoboard/templates/bingoboards/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="my-tasks-list">
    <h1>My Bingo Games</h1>
    <a href="{% url 'bingo_game_create' %}">Create new game</a>
    {% if bingogame_list|length == 0 %}
    <p>You have no games</p>
    {% else %}
    <table>
      <thead>
          <tr>
              <th>Game name</th>
              <th>Created on</th>
          </tr>
      </thead>
      <tbody>
        {% for game in bingogame_list %}
              <tr>
                  <td><a href="{% url 'bingo_game' pk=game.id %}">{{game.name}}</a></td>
                  <td>{{game.created_on}}</td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
  {% endif %}
</main>

{% endblock content %}

bingoboard/templates/bingoboards/new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form">
            <h1>Create a Belay Bingo Game</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}